### ISSUE TITLE
still can get this app, please?

### ISSUE THREAD

**Issue by Juris3D** [darkxeno/DrumCloud#2]
Hello. Sorry i am bothering on this old one, but - is this DrumCloud still downloadable as apk somewhere? Store link is dead, and Google search gives just suspicious "download places" I'd rather avoid. Can I try this old app, please? :) OR, should I look for something more recent instead? Thank You!

**Comment by darkxeno** [comment]
Thank you for your interest on DrumCloud, unfortunatelly the app was not
maintained from a few years ago, and due to updates on the Google Play policies
got removed from the store.

As you found out the APK was uploaded to a few other stores but I dont know
if those versions are compatible with the current Android OS versions, you
can try checking on the Amazon App Store for example. If that don't work,
look for a similar product on the Google Play store.

Sorry for not being of more help.


PS: tried the APK from apk-pure.com and was working fine, except for the sequencer  where navigation its somehow buggy.
